/*
 * File: app/store/JsonStoreFuga.js
 *
 * This file was generated by Sencha Architect version 3.5.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MobileSapac.store.JsonStoreFuga', {
    extend: 'Ext.data.Store',

    requires: [
        'MobileSapac.model.fuga',
        'Ext.data.proxy.JsonP',
        'Ext.data.reader.Json'
    ],

    config: {
        model: 'MobileSapac.model.fuga',
        storeId: 'JsonStoreFuga',
        proxy: {
            type: 'jsonp',
            reader: {
                type: 'json'
            }
        }
    }
});