/*
 * File: app/store/JsonStoreFaltaServicio.js
 *
 * This file was generated by Sencha Architect version 3.5.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MobileSapac.store.JsonStoreFaltaServicio', {
    extend: 'Ext.data.Store',

    requires: [
        'MobileSapac.model.faltaServicio',
        'Ext.data.proxy.JsonP',
        'Ext.data.reader.Json'
    ],

    config: {
        autoLoad: true,
        model: 'MobileSapac.model.faltaServicio',
        storeId: 'JsonStoreFaltaServicio',
        proxy: {
            type: 'jsonp',
            url: 'http://127.0.0.1/webappcore/service.php?serviceName=getAll&object=usuario&jsonp=true',
            reader: {
                type: 'json',
                messageProperty: 'message',
                rootProperty: 'object',
                successProperty: 'status'
            }
        }
    }
});