/*
 * File: app/controller/MyController.js
 *
 * This file was generated by Sencha Architect version 3.5.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MobileSapac.controller.MyController', {
    extend: 'Ext.app.Controller',

    config: {
        refs: {
            InitialView: {
                selector: '#InitialView',
                xtype: 'Ext.navigation.View'
            }
        },

        control: {
            "button#savebutton": {
                tap: 'onMybutton2Tap'
            }
        }
    },

    onMybutton2Tap: function(button, e, eOpts) {
        console.debug("test");
        //Ext.Msg.alert('Alert', 'test', Ext.emptyFn);


        //var cities = TAFFY([{name:"New York",state:"WA"},{name:"Las Vegas",state:"NV"},{name:"Boston",state:"MA"}]);

        //cities.store("ciudades");

        //cities.insert({name:"Portland",state:"OR"});

        this.getInitialView().push({
            xtype: 'ReporteFugasPanel',
            title: 'Reporte fuga'
        });

    }

});