/*
 * File: app/view/MainPanel.js
 *
 * This file was generated by Sencha Architect version 3.5.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MobileSapac.view.MainPanel', {
    extend: 'Ext.form.Panel',
    alias: 'widget.MainPanel',

    requires: [
        'Ext.Toolbar',
        'Ext.Button',
        'Ext.TitleBar'
    ],

    config: {
        itemId: 'myformpanel',
        items: [
            {
                xtype: 'toolbar',
                docked: 'bottom',
                height: '10%',
                maxHeight: '10%',
                ui: 'light',
                layout: {
                    type: 'hbox',
                    align: 'center',
                    pack: 'center'
                },
                items: [
                    {
                        xtype: 'button',
                        ui: 'plain',
                        iconAlign: 'top',
                        iconCls: 'home'
                    },
                    {
                        xtype: 'button',
                        ui: 'plain',
                        width: 46,
                        iconAlign: 'top',
                        iconCls: 'organize',
                        text: 'MyButton7'
                    }
                ]
            },
            {
                xtype: 'titlebar',
                docked: 'top'
            }
        ]
    }

});