/*
 * File: app/view/MyFormPanel.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.MyFormPanel', {
    extend: 'Ext.form.Panel',

    requires: [
        'Ext.field.Password',
        'Ext.field.DatePicker',
        'Ext.picker.Date',
        'Ext.Button',
        'Ext.field.Spinner',
        'Ext.field.Toggle',
        'Ext.field.Checkbox'
    ],

    config: {
        items: [
            {
                xtype: 'passwordfield',
                label: 'Pass'
            },
            {
                xtype: 'textfield',
                label: 'login'
            },
            {
                xtype: 'datepickerfield',
                label: 'Field',
                placeHolder: 'mm/dd/yyyy'
            },
            {
                xtype: 'spinnerfield',
                label: 'Field'
            },
            {
                xtype: 'togglefield',
                label: 'Field'
            },
            {
                xtype: 'sliderfield',
                label: 'Field'
            },
            {
                xtype: 'button',
                text: 'MyButton2'
            },
            {
                xtype: 'checkboxfield',
                label: 'Field'
            },
            {
                xtype: 'numberfield',
                label: 'Field'
            }
        ]
    }

});