/*
 * File: app/view/ReporteFugasPanel.js
 *
 * This file was generated by Sencha Architect version 3.5.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MobileSapac.view.ReporteFugasPanel', {
    extend: 'Ext.Panel',
    alias: 'widget.ReporteFugasPanel',

    requires: [
        'Ext.Map',
        'Ext.Toolbar',
        'Ext.Button',
        'Ext.field.TextArea'
    ],

    config: {
        items: [
            {
                xtype: 'map',
                height: 200
            },
            {
                xtype: 'toolbar',
                docked: 'bottom',
                items: [
                    {
                        xtype: 'button',
                        ui: 'confirm',
                        text: 'Reportar'
                    }
                ]
            },
            {
                xtype: 'textareafield',
                label: 'Observaciones',
                labelAlign: 'top'
            }
        ]
    }

});